server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: sale-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/sales

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring:application:name}
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitBreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 8
        minimumNumberOfCalls: 4
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      product-cb:
        baseConfig: default
      costumer-cb:
        baseConfig: default